### ISSUE TITLE
Can't watch youtube video.

### ISSUE THREAD

**Issue by m-schuetz** [qdot/deldo#4]
They require an age verification process that I'm not keen on following up with. Perhaps there are other sites starting with "you____" that could host the video?

**Comment by Strappazzon** [comment]
> They require an age verification process that I'm not keen on following up with. Perhaps there are other sites starting with "you____" that could host the video?

https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass

**Comment by qdot** [comment]
Someone over on HN posted this bypass link that seems to do the trick: https://invidio.xamh.de/watch?v=D1sXuHnf_lo

**Comment by qdot** [comment]
Updated the readme with that link, closing.
